### ISSUE TITLE
Why     text = " ".join(text.split())    in __getitem__ in Transformers_multilabel_distilbert?

### ISSUE THREAD

**Issue by joawar** [DhavalTaunk08/NLP_scripts#2]
The code I'm referring to is in cell 8 in https://github.com/DhavalTaunk08/NLP_scripts/blob/master/Transformers_multilabel_distilbert.ipynb
I tried to print before and after this line, and I see no difference.
```python
print(text)
print(repr(text))
text = " ".join(text.split())
print(text)
print(repr(text))
```
Output:
```console
proving there is no cure for stupidity.
'proving there is no cure for stupidity.'
proving there is no cure for stupidity.
'proving there is no cure for stupidity.'
```

Maybe it makes a difference in certain cases? Or can I just remove this line?

**Comment by DhavalTaunk08** [comment]
Yes, in your case it is not useful. But it is useful in cases where there are multiple spaces between the words. Hope this solves your concern!!

**Comment by joawar** [comment]
Thanks a lot for the quick reply and explanation! And also for the tutorial of course!
