### ISSUE TITLE
The test score on Kaggle seems quiet low

### ISSUE THREAD

**Issue by DerekGrant** [DhavalTaunk08/NLP_scripts#3]
I modify it and then predict the test.tsv and submit to kaggle  sentiment competition. The score is quite low, much lower than BERT, so how much epoch will be better. For Bert, I just use 3 epoch, but increase epoch in this roberta seems not work.

**Comment by DhavalTaunk08** [comment]
You can try tuning the parameters or adding more layers at the end. That should work. Let me know if you face any issues.
